Timestamp support
sphinx-contrib/youtube pull request #19
Opened 2021-08-28 18:30 UTC by Robpol86

Adding optional parameter `:timestamp:` for both YouTube and Vimeo
videos.

Fixes https://github.com/sphinx-contrib/youtube/issues/17

2021-08-28 18:47 UTC, Robpol86 commented
Hmm the youtube part doesn't seem to work actually. I was fooled by YouTube since it caches the last time I viewed the video. Tested in incognito mode and it seems to ignore timestamping. Gonna close this for now until I can figure something out.

2021-08-28 19:07 UTC, Robpol86 commented
Fixed, need to use "start" instead of "t".

2021-08-31 19:52 UTC, dham requested changes
Thanks for this nice contribution. I just have two concerns. One is that the timestamp seems to be dropped in LaTeX output, and the other is  what would happen if someone wanted to add more of the URL parameters that YouTube and/or Vimeo support.

I think that both of these can be fixed fairly easily. The first thing to do is to lift the processing of `:timestamp:` into a URL parameter from the html handler up to `Video.run`. This would enable this code to be shared by different backends (because it's not backend-specific). Then, the argument to `_node` could just be called something like `url_parameters`. This indicates that any future parameters should be handled in `run` and just added to this argument.

This approach could then be supported in LaTeX output by simply giving `\sphinxcontribyoutube` a third argument to contain the url parameters.

Cheers,

David

2021-09-19 09:30 UTC, akihironitta commented
I'm considering utilising this extension in https://github.com/PyTorchLightning/pytorch-lightning/pull/7688. Any updates on this PR?

2021-09-19 15:58 UTC, Robpol86 commented
I'm currently working on another project but I plan on getting back to this some time next week.

2021-11-11 15:15 UTC, dham requested changes
Thanks. I think this is basically good. I just found one tiny bug with parameter numbers.

2021-11-11 15:15 UTC, dham commented on README.rst
> +    \newcommand{\sphinxcontribvimeo}[2]{\begin{quote}\begin{center}\fbox{\url{#1#2#3}}\end{center}\end{quote}}
needs to be `[3]` to indicate that the command takes 3 parameters.

2021-11-11 15:15 UTC, dham commented on sphinxcontrib/youtube/utils.py
> +        \newcommand{%s}[2]{\begin{quote}\begin{center}\fbox{\url{#1#2#3}}\end{center}\end{quote}}
As above, needs to be `[3]`

2021-11-11 17:14 UTC, Robpol86 commented
Good catch. Fixed

2021-12-07 12:36 UTC, goverfl0w commented
@dham bumping.

2022-02-01 11:16 UTC, merged