Fixes for compatibility
sphinx-contrib/youtube pull request #20
Opened 2021-09-07 18:12 UTC by TunaLobster

These are 2 commits that solve issues when building with python 2, 3.5, and others. Python f strings were added in 3.5. Using a function wrapper without functools.partial creates the proper attributes that docutils nodes.py is looking for and matches the example nodes from sphinx.

Solves `AttributeError: 'functools.partial' object has no attribute '__name__'` error from docutils nodes.py

Tested with the ArduPilot documentation using python 2 and 3.

Rant: Since the tags for releases that worked with those version are no longer present and the version number was never bumped, fixing it here is the best option. Replicating a build environment that is using an old dev tag version is much more difficult because those tags are gone and the version number has not been bumped with each new release. This makes it far more frustrating than other python packages to track down which git hash to use with pip install.

2021-09-12 19:36 UTC, dham requested changes
Thanks for catching the issue with `partial`, I agree with your fix here.

I don't think that going back from f-strings to `.format` is warranted. `f-strings` were introduced in Python 3.6. That is now the oldest security-patched Python. Both 2.7 and 3.5 are now officially end of life and don't receive even critical security fixes. I also note that Sphinx itself has a hard requirement for Python 3.6 [in its `setup.py`](https://github.com/sphinx-doc/sphinx/blob/ba2439a105e5a68a44dd3f839e86332889cce451/setup.py#L13). I think it's therefore reasonable for a Sphinx plugin to assume Python >=3.6 .

With respect to the "rant" in the PR, no tags have been removed from this repository. I only got control of the PyPI project for this plugin in July 2021, and in August I made the first release in many years. I don't know why the previous maintainer didn't tag the releases in the repository, though I can believe that this practice was less well developed in 2014.

Cheers,

David

2021-09-12 21:52 UTC, TunaLobster commented
That assumes that all environments out there are using a sphinx>=4.0 release. There are many build environments still out there running older versions of sphinx and looking for a youtube embedding plugin that will work when pulled. Creating code to work with the widest variety of systems should always be the priority unless it is really specialized. I don't see any reason, in this case, to us an f-string when .format or % formatting would work perfectly fine. They are short strings so there is hardly any penalty in readability. There is no large desire for an f-string speed increase with this node as it is be less used than many other things in sphinx.

Why use an f-string here?

2021-09-13 08:57 UTC, dham commented
The reason to use an `f-string` here is that it's more readable to have the substitution in the string than at the end. The Sphinx version here is not the issue - this code will work with older Sphinx. The issue is the Python version. For `f-strings` to not work for you, your Python needs be so old that it no longer even gets security updates. Surely the right answer is to expect users to run a supported version of Python.

2021-09-13 12:59 UTC, TunaLobster commented
I really do not agree with the readability argument in the case. It has no standing. The movement of variables is less than 20 characters and the remain on the same line. The only cases where I would see f-string readability being a valid argument would for very long, multiline strings. We've been reading .format strings for decades and not just in python. This is really not an unexpected syntax to come across. Why only f-strings in these places? Why not make everything f-strings? Why not be consistent?

You directly linked to a commit included with sphinx 4.0 tags. It is true that python 3.6 is a requirement, but only if the build environment is running sphinx 4.0+. That's not the case however. But since there were no tags created for a non-compatible version that would be easy to rollback to in an environment install script, there's now hardly an easy way to provide compatibility beyond forking. For other build environments, they can remain on sphinx 3 for a while before needing to update their environment. They'll notice the warning or build error, add something to their todo list, pip install sphinx 3.whatever, and then they will get to it later.

For a localized build environment, especially sphinx, how many of those security updates are directly impactful to say the html builder? Latex builder? Probably none of them. So why require them?

2021-09-13 20:15 UTC, dham commented
I'm sorry that we disagree, however I have no interest in a prolonged debate. I think it's reasonable for a package to use features that are in all the currently maintained Python releases, and that is what is done here. 

What I'm going to do is merge this PR and put out a release. That will give you a release that works on the Python versions you want. You and anyone else who wants to use unmaintained Python versions can pin on that release.

However, that does not constitute an undertaking not to use new features in future commits. In particular, I think f-strings are preferable in most cases and I will continue to use them in this project. My position is that anything in Python 3.6 is currently fair game and that will move on to Python 3.7 on December 23 this year when Python 3.6 reaches end of life.

2021-09-13 20:15 UTC, dham approved these changes

2021-09-13 20:15 UTC, merged