download the thumbnails from the ID
sphinx-contrib/youtube pull request #28
Opened 2022-02-01 17:05 UTC by 12rambau

Fix #24 and Fix #11. Using the ID of the video, the thumbnails are downloaded to the output directory. They are stored in a _video_thumbnail directory using their id as name meaning that this video:

```rst
..  youtube:: dQw4w9WgXcQ
```

will download the following image in a `_video_thumbnail/dQw4w9WgXcQ.jpeg` file.

![rick roll](https://i3.ytimg.com/vi/dQw4w9WgXcQ/maxresdefault.jpg)

Files are downloaded only once to reduce the size of the output file. Some output are send to the user. 

```rst
Mise à jour de l'environnement : 0 ajouté(s), 1 modifié(s), 0 supprimé(s)
Lecture des sources... [100%] index
https://i3.ytimg.com/vi/dQw4w9WgXcQ/maxresdefault.jpg -> /Users/pierrickrambaud/Documents/travail/FAO/app_buffer/youtube/docs/build/html/_video_thumbnail/dQw4w9WgXcQ.jpg (already in cache)
```

The Latex default output remains the same but i updated the readme with an example of custom command using these images. 

Also note that for testing purposes I created a single page documentation output, everything is up and ready to be linked to a RDT page if you want. It needs to install the "doc" requirements as set-up in the readthedocs.yaml file.

I added the requests lib to the requirements. Everything could also be handled with `distutil` but I prefers `requests`... let me know If you want me to change it. 

Happy to read your comments !

2022-05-16 05:48 UTC, dham requested changes
Thanks for this and sorry for not getting back to it earlier. All my teaching is in spring term and other things get forgotten.

The core functionality here I'm fine with.

I am nervous about the documentation changes, because now we have to maintain documentation in two places.

I guess doing RTD is OK, but then we should cut back the README to minimal install information and a link to RTD, so that future documentation only goes in the one place.

2022-05-16 05:48 UTC, dham commented on README.rst
> +The user may customise the rendering of the URL by defining this command in the preamble. The captions will be downloaded to the latex folder and can thus be used as images in the :code:`.pdf` docume
Typo: "this needs"

2022-05-16 05:48 UTC, dham commented on README.rst
> +This example will show the video as a figure using the thumbnail as image and the url as caption (clickable link). This is the one we use for this very documentation. rember that the argument of your
typo: remember

2022-05-17 06:23 UTC, 12rambau commented
Thanks for your review, I updated the docs and README with both the typos and the privacy mode. Do you want me to reduce the length of the README in this PR or do you prefer to first publish the docs on RDT and then cut the readme once it's online ?

2022-06-03 04:23 UTC, dham approved these changes

2022-06-03 04:23 UTC, merged