add installation process
sphinx-contrib/youtube pull request #49
Opened 2023-02-19 09:32 UTC by 12rambau

mainly to add the extention package name which was a request of one of my coleague (looking for a youtube package for 3 days)  
Also updated the tox file as [whitelist](https://tox.wiki/en/latest/changelog.html#deprecations-and-removals-4-0-0rc4) is now deprecated.   
Fix #48

2023-02-19 20:46 UTC, dham approved these changes

2023-02-19 20:47 UTC, dham requested changes

2023-02-19 20:47 UTC, dham commented on docs/source/index.rst
> +The package is avalaible on `pipy <https://pypi.org/project/sphinxcontrib-youtube/1.2.0/>`__ and can be installed with pip:
Please change this to the unversioned link as this link will go out of date rapidly.

2023-03-30 08:04 UTC, 12rambau commented
converting it to draft until #53 get reviews as I would need to change this documentation location (or more likely start from scratch)

2023-05-01 12:07 UTC, dham commented
Superceded by #54

2023-05-01 12:07 UTC, closed without merging