Add peertube support
sphinx-contrib/youtube pull request #59
Opened 2023-07-21 19:08 UTC by Murmele

2023-07-21 19:10 UTC, Murmele commented on README.rst
> +      :server: peertube.tv
```suggestion
      :instance: peertube.tv
```

2023-07-21 19:10 UTC, Murmele commented on docs/usage.rst
> +      :server_url: "peertube.tv"
```suggestion
      :instance: "peertube.tv"
```

2023-07-21 19:10 UTC, Murmele commented on tests/roots/test-video/peertube.rst
> +   :server_url: "peertube.tv"
```suggestion
   :instance: "peertube.tv"
```

2023-07-28 17:06 UTC, Murmele commented
@dham

2023-07-31 08:47 UTC, Murmele commented on docs/usage.rst
> +   .. peertube:: 486557682
```suggestion
   .. peertube:: 327a21b3-374e-4373-8b2c-494c9f5e1f19
```

2023-07-31 08:47 UTC, Murmele commented on docs/usage.rst
> +      :instance: "peertube.tv"
```suggestion
      :url_parameters: "?start=0s"
```

2023-09-12 08:01 UTC, dham requested changes

2023-09-12 08:01 UTC, dham commented on docs/usage.rst
> +   \sphinxcontribPeerTube{https://peertube.tv/w/}{327a21b3-374e-4373-8b2c-494c9f5e1f19}{?start=43}
To be consistent, please use lower case in the macro name.

2023-09-18 10:20 UTC, dham commented on docs/usage.rst
> +   \sphinxcontribPeerTube{https://peertube.tv/w/}{327a21b3-374e-4373-8b2c-494c9f5e1f19}{?start=43}
```suggestion
   \sphinxcontribpeertube{https://peertube.tv/w/}{327a21b3-374e-4373-8b2c-494c9f5e1f19}{?start=43}
```

2023-09-18 10:30 UTC, dham requested changes

2023-09-18 10:30 UTC, dham commented on tests/test_build.py
> +    assert r"\newcommand{\sphinxcontribPeerTube}" in result
```suggestion
    assert r"\newcommand{\sphinxcontribpeertube}" in result
```

2023-09-18 10:30 UTC, dham commented on tests/test_build.py
> +        r"\sphinxcontribPeerTube{https://peertube.tv/w/}{327a21b3-374e-4373-8b2c-494c9f5e1f19}{}"
```suggestion
        r"\sphinxcontribpeertube{https://peertube.tv/w/}{327a21b3-374e-4373-8b2c-494c9f5e1f19}{}"
```

2023-09-18 10:53 UTC, dham commented on sphinxcontrib/youtube/peertube.py
> +    _platform = "PeerTube"
```suggestion
    _platform = "peertube"
```

2023-09-18 10:55 UTC, dham approved these changes

2023-09-18 10:56 UTC, merged

2023-10-09 07:45 UTC, Murmele commented
Sorry I was on holiday. Shall I change anything?

2023-10-09 09:41 UTC, dham commented
As you can see from the commit record, the changes were minor so I made them myself using GithHub's suggestion feature. This has now been merged and is in the 1.4 release on PyPI. Thanks for your contribution!

2023-10-09 12:58 UTC, Murmele commented
Thanks for merging!